//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgi
    {
        public int SICIL_NO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string GOREVI { get; set; }
        public Nullable<System.DateTime> IS_BASLANGIC_TARIH { get; set; }
    }
}
